config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'home', to: 'pages#home', as: 'home'
  get "pages/download_pdf"
  get 'resume', to: 'pages#resume', as: 'resume'

  get 'black_and_white_landing', to: 'black_and_white#landing'

  resources :inbounds, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbound.rb
class Inbound < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/black_and_white_controller.rb
class BlackAndWhiteController < ApplicationController
  def landing
  end
end

app/controllers/inbounds_controller.rb
class InboundsController < ApplicationController
  def new
    @inbound = Inbound.new
  end
  def create
    @inbound = Inbound.create(inbound_params)

    if @inbound.save
      flash[:notice] = "Thank you! Tom will be in touch shortly."
      redirect_to root_path(anchor: 'contact')
    else
      flash[:alert] = "Looks like there may be an error in your submission—please make sure you list a name and correctly formatted email address."
      redirect_to root_path(anchor: 'contact')
    end
  end

  private

  def inbound_params
    params.require(:inbound).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @inbound = Inbound.new
  end

  def resume
  end

  def download_pdf
    send_file(
      "#{Rails.root}/app/assets/images/tmp_resume.pdf",
      filename: "thomas-patton.pdf",
      type: "application/pdf"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/black_and_white/landing.html.erb
<div class="landing">
  <div class="navigation">
    <div class="logo">
    </div>
    <div class="links">
      <a href="">Link One</a>
      <a href="">Link Two</a>
      <a href="">Link Three</a>
    </div>
  </div>
  <div class="hero">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <title>Thomas Matthew Patton</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag 'tmp_logo.png' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-126771198-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-126771198-1');
    </script>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Sidebar Naviagation -->
<div class="hidden-xs">
  <div id="sidebar">
    <div class="scroll-downs">
      <div class="mousey">
        <div class="scroller"></div>
      </div>
    </div>
    <ul>
      <%= image_tag "tmp_logo_side.svg", class: "sidebar_logo" %>
      <li id="hme"><a href="#home">Home</a></li>
      <li id="wia"><a href="#who_i_am">About me</a></li>
      <li id="wid"><a href="#what_i_do">What I do</a></li>
      <li id="mw"><a href="#my_work">My work</a></li>
      <li id="ctsb"><a href="#contact">Contact</a></li>
      <li><%= link_to 'Résumé', resume_path %> </li>
    </ul>
  </div>
</div>

<!-- Dropdown appearing on mobile only -->
<div class="hidden-md hidden-lg hidden-sm">
  <div class="navbar-wagon">
    <!-- Logo -->
      <a href="/" class="navbar-wagon-brand">
        <%= image_tag "tmp_logo_side.svg", class: "sidebar_logo" %>
      </a>
  </div>
</div>

  <!-- Mobile HTML -->
<div class="hidden-lg hidden-md hidden-sm">
  <div class="banner" style="background-image: url(https://images.unsplash.com/photo-1514621166532-aa7eb1a3a2f4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1ab428e21d89e5fc9eb58c31273c3751&auto=format&fit=crop&w=934&q=80)">
    <div id="mobile_home">
      <div class="mobile_home__text">
        <div class="mobile_home__name">
          <p>My name's Tom Patton.</p>
        </div>
        <div class="mobile_home__sub">
          <p>Product focused business leader, web designer, and developer in San Francisco working with businesses, entrepeneurs, and freelancers.</p>
        </div>
        <a class='btn_block_white' href="#mobile_contact">SAY HELLO!</a>
        <div class="mobile_home_scroller">
          <div class="mousey">
            <div class="scroller"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="mobile_who_i_am">
    <h1 class="mobile_who_i_am__title">Hi there.</h1>
    <div class="mobile_who_i_am__para">
      <p>I’m a business strategy professional, web designer, and developer. I can help you market, design, and launch your freelance website, blog, or startup MVP. </p>
    </div>
    <div class="mobile_who_i_am__links">
      <a class="mobile_who_i_am__link"href="#contact">CONTACT</a>
      <a class="mobile_who_i_am__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
      <a class="mobile_who_i_am__link" href="https://github.com/tompatton2">GITHUB</a>
      <a class="who_i_am__link"href="/resume">RESUME</a>
    </div>
  </div>

  <div id="mobile_what_i_do">
    <h1 class="mobile_what_i_do__title">What I can do for you</h1>
    <div class="mobile_what_i_do_container">
      <div class="mobile_what_i_do__element" data-aos="zoom-in">
        <div class="what_i_do_top">
            <%= image_tag "suitcase.svg", class: "mobile_what_i_do__icon" %>
            <p class="mobile_what_i_do__header">BUSINESS</p>
            <p class="mobile_what_i_do__text">My background is in business strategy, management, and operations. I have a diverse business skill set and can help you qualify business ideas, size markets, manage projects, create go-to-market stategies, and measure impact.</p>
        </div>
        <div class="what_i_do__bottom">
          <p class="what_i_do_header what_i_do_header-sub"><strong>DISCIPLINES</strong></p>
          <ul>
            <li>RESEARCH</li>
            <li>POSITIONING</li>
            <li>MANAGEMENT</li>
            <li>MARKETING</li>
            <li>ANALYTICS</li>
          </ul>
        </div>
      </div>
      <div class="mobile_what_i_do__element" data-aos="zoom-in">
        <div class="what_i_do_top">
          <%= image_tag "pencil.svg", class: "mobile_what_i_do__icon" %>
          <p class="mobile_what_i_do__header">DESIGN</p>
          <p class="mobile_what_i_do__text">I come from a family of architects and artists, and design has always been my hobby and passion. I can help create product one-pagers, social media content, client and investor presentations, as well as product prototypes.</p>
        </div>
        <div class="what_i_do__bottom">
          <p class="what_i_do_header what_i_do_header-sub"><strong>TOOLS</strong></p>
          <ul>
            <li>PEN & PAPER</li>
            <li>SKETCH - FIGMA</li>
            <li>INVISION</li>
            <li>ADOBE SUITE</li>
            <li>TRELLO - JIRA</li>
          </ul>
        </div>
      </div>
      <div class="mobile_what_i_do__element" data-aos="zoom-in">
        <div class="what_i_do_top">
          <%= image_tag "html.svg", class: "mobile_what_i_do__icon" %>
          <p class="mobile_what_i_do__header">DEVELOPMENT</p>
          <p class="mobile_what_i_do__text">Full-stack web development to help you implement your business website, blog, or startup MVP.</p>
        </div>
        <div class="what_i_do__bottom">
          <p class="what_i_do_header what_i_do_header-sub"><strong>LANGUAGES</strong></p>
          <ul>
            <li>RUBY</li>
            <li>RUBY ON RAILS</li>
            <li>JAVASCRIPT</li>
            <li>HTML & CSS</li>
            <li>SQL</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="my_work__background">
    <div id="mobile_my_work">
      <h1 class="mobile_my_work__title">The things I've made</h1>
      <div class="mobile_my_work__container">
<!--         <div class="mobile_my_work__header">
          <p>WEB APPS</p>
        </div> -->
        <div class="mobile_my_work__item">
          <div data-aos="zoom-in-up">
            <a href="https://stacker-about.herokuapp.com"  target="_blank">
              <%= image_tag "stacker_tiny.png", class: "mobile_carousel_image mobile_carousel_image-computer" %>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="mobile_contact">
    <h1 class="mobile_contact__title">Let's talk.</h1>
    <%= render 'shared/flashes' %>
    <div class="contact__container">
      <div class="contact__form">
        <div class="form">
          <%= form_for @inbound do |c| %>
          <div class="form__content">
            <%= c.label :name, "Name" %>
            <%= c.text_field :name %>
            <%= c.label :email, "Email" %>
            <%= c.text_field :email %>
            <%= c.label :message, "Message" %>
            <%= c.text_area :message, :class => 'form__message' %>
          </div>
          <%= c.submit 'Contact Tom', :class => 'btn_transparent_white'%>
          <% end %>
        </div>
      </div>
      <div class="contact__links">
        <a class="mobile_contact__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
        <a class="mobile_contact__link" href="https://github.com/tompatton2">GITHUB</a>
        <a class="mobile_contact__link"href="mailto:tom.patton22@gmail.com">EMAIL</a>
        <a class="mobile_contact__link"href="/resume">RESUME</a>
      </div>
    </div>
  </div>
</div>

  <!-- Desktop HTML -->
<div class="hidden-xs">
  <div class="page_container">
    <div class="banner" style="background-image: url(https://images.unsplash.com/photo-1514621166532-aa7eb1a3a2f4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1ab428e21d89e5fc9eb58c31273c3751&auto=format&fit=crop&w=934&q=80)">
      <div id="home">
        <div class="home__text">
          <div class="home__name">
            <p>My name's Tom Patton.</p>
          </div>
          <div class="home__sub">
            <p>Product focused business leader, web designer, and developer in San Francisco working with businesses, entrepeneurs, and freelancers.</p>
          </div>
          <div class="home__button">
            <a id="cta" class='btn_block_white' href="#contact">SAY HELLO.</a>
          </div>
        </div>
      </div>
    </div>

    <div id="who_i_am">
      <h1 class="who_i_am__title">Hi there.</h1>
      <div class="who_i_am__para">
        <p>I’m a business strategy professional, web designer, and developer. I can help you market, design, and launch your freelance website, blog, or startup MVP.</p>
      </div>
      <div class="who_i_am__links">
        <a class="who_i_am__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
        <a class="who_i_am__link" href="https://github.com/tompatton2">GITHUB</a>
        <a class="who_i_am__link"href="/resume">RESUME</a>
      </div>
    </div>

    <div id="what_i_do">
      <h1 class="what_i_do__title">What I can do for you</h1>
      <div class="what_i_do_container">
        <div class="what_i_do__element">
          <div class="what_i_do_top">
            <%= image_tag "suitcase.svg", class: "what_i_do__icon" %>
            <p class="what_i_do__header">BUSINESS</p>
            <p class="what_i_do__text">My background is in business strategy, management, and operations. I have a diverse business skill set and can help you qualify business ideas, size markets, manage projects, create go-to-market stategies, and measure impact.</p>
          </div>
          <div class="what_i_do__bottom">
            <p class="what_i_do_header what_i_do_header-sub"><strong>DISCIPLINES</strong></p>
            <ul>
              <li>RESEARCH</li>
              <li>POSITIONING</li>
              <li>MANAGEMENT</li>
              <li>MARKETING</li>
              <li>ANALYTICS</li>
            </ul>
          </div>
        </div>
        <div class="what_i_do__element">
          <div class="what_i_do_top">
            <%= image_tag "pencil.svg", class: "what_i_do__icon" %>
            <p class="what_i_do__header">DESIGN</p>
            <p class="what_i_do__text">I come from a family of architects and artists, and design has always been my hobby and passion. I can help create product one-pagers, social media content, client and investor presentations, as well as product prototypes.</p>
          </div>
          <div class="what_i_do__bottom">
            <p class="what_i_do_header what_i_do_header-sub"><strong>TOOLS</strong></p>
            <ul>
              <li>PEN & PAPER</li>
              <li>SKETCH - FIGMA</li>
              <li>INVISION</li>
              <li>ADOBE SUITE</li>
              <li>TRELLO - JIRA</li>
            </ul>
          </div>
        </div>
        <div class="what_i_do__element">
          <div class="what_i_do_top">
            <%= image_tag "html.svg", class: "what_i_do__icon" %>
            <p class="what_i_do__header">DEVELOPMENT</p>
            <p class="what_i_do__text">Full-stack web development to help you implement your business website, blog, or startup MVP.</p>
          </div>
          <div class="what_i_do__bottom">
            <p class="what_i_do_header what_i_do_header-sub"><strong>LANGUAGES</strong></p>
            <ul>
              <li>RUBY</li>
              <li>RUBY ON RAILS</li>
              <li>JAVASCRIPT</li>
              <li>HTML & CSS</li>
              <li>SQL</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="my_work__background">
      <div id="my_work">
        <h1 class="my_work__title">The things I've made</h1>
        <div class="my_work__container">
          <!-- <div class="my_work__header">
            <p>WEB APPS</p>
          </div> -->
          <div class="my_work__item">
            <div data-aos="zoom-in-up">
              <a href="https://stacker-about.herokuapp.com"  target="_blank">
                <%= image_tag "stacker_tiny.png", class: "carousel_image" %>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="contact">
      <h1 class="contact__title">Let's talk.</h1>
      <%= render 'shared/flashes' %>
      <div class="contact__container">
        <div class="contact__form">
          <div id="contact_form__remove" class="form">
            <%= form_for @inbound do |c| %>
            <div class="form__content">
              <%= c.label :name, "Name" %>
              <%= c.text_field :name %>
              <%= c.label :email, "Email" %>
              <%= c.text_field :email %>
              <%= c.label :message, "Message" %>
              <%= c.text_area :message, :class => 'form__message' %>
            </div>
            <%= c.submit 'Contact Tom', :class => 'btn_transparent_white'%>
            <% end %>
          </div>
        </div>
        <div class="contact__links">
          <a class="contact__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
          <a class="contact__link" href="https://github.com/tompatton2">GITHUB</a>
          <a class="contact__link"href="mailto:tom.patton22@gmail.com">EMAIL</a>
          <a class="contact__link" href="/resume">RESUME</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<h1>Hello World</h1>

app/views/pages/resume.html.erb
<!-- Sidebar Naviagation -->
<div class="hidden-xs">
  <div id="sidebar">
    <ul>
      <%= image_tag "tmp_logo_side.svg", class: "sidebar_logo" %>
      <li id="hme"><a href="/">Home</a></li>
      <li id="wia"><a href="/#who_i_am">About me</a></li>
      <li id="wid"><a href="/#what_i_do">What I do</a></li>
      <li id="mw"><a href="/#my_work">My work</a></li>
      <li id="ct"><a href="/#contact">Contact</a></li>
      <li><%= link_to 'Résumé', resume_path %> </li>
    </ul>
  </div>
</div>

<!-- Dropdown appearing on mobile only -->
<div class="hidden-md hidden-lg hidden-sm">
  <div class="navbar-wagon">
    <!-- Logo -->
      <a href="/" class="navbar-wagon-brand">
        <%= image_tag "tmp_logo_side.svg", class: "sidebar_logo" %>
      </a>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/#mobile_home">Home</a></li>
        <li><a href="/#mobile_who_i_am">About me</a></li>
        <li><a href="/#mobile_what_i_do">What I do</a></li>
        <li><a href="/#mobile_my_work">My work</a></li>
        <li><a href="/#mobile_contact">Contact</a></li>
        <li><%= link_to 'Résumé', resume_path %> </li>
      </ul>
    </div>
  </div>
</div>


<div class="hidden-xs">
  <div class="page_container">
    <div class="resume__wrapper">
      <div class="resume__elements">
          <%= image_tag "thomas_matthew_patton.png", class: "resume__page" %>
          <%= link_to 'Download PDF', pages_download_pdf_url, :class => 'btn_transparent_white' %>
          <div class="contact__links">
            <a class="contact__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
            <a class="contact__link" href="https://github.com/tompatton2">GITHUB</a>
            <a class="contact__link"href="mailto:tom.patton22@gmail.com">EMAIL</a>
          </div>
        </div>
      </div>
    </div>
</div>


<div class="hidden-lg hidden-sm hidden-md">
  <div class="resume__wrapper">
    <div class="resume__elements">
        <%= image_tag "thomas_matthew_patton.png", class: "mobile_resume__page" %>
        <%= link_to 'Download PDF', pages_download_pdf_url, :class => 'btn_transparent_white' %>
        <div class="contact__links">
          <a class="mobile_contact__link"href="https://www.linkedin.com/in/tom-patton">LINKEDIN</a>
          <a class="mobile_contact__link" href="https://github.com/tompatton2">GITHUB</a>
          <a class="mobile_contact__link"href="mailto:tom.patton22@gmail.com">EMAIL</a>
          <a class="mobile_contact__link" href="/resume">RESUME</a>
        </div>
    </div>
  </div>
</div

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>